


#+TITLE: SPARC Anatomy Working Group
#+HTML_HEAD: <meta name="version" content="0.0.1" />
#+OPTIONS: num:nil html-preamble:t H:2
#+SETUPFILE: theme-readtheorg-local.setup
# [[./sawg.html][local development]]
# [[http://ontology.olympiangods.org/trees/sparc][testing]]
# [[http://ontology.neuinfo.org/trees/sparc][production]]

* Developer notes                                                 :noexport:
  This is a self publishing document!
  TODO import code from thesis.org to automate publishing.
  
** Publishing
   Tangle both blocks here =C-c C-v C-t= (=t= also works) and then you
   can publish this document by running =../bin/publish-sawg= with
   =AUX_RESOLVER_HOST= set in your environment (.e.g via =~/.bashrc=).
   #+NAME: publish
   #+BEGIN_SRC emacs-lisp :eval never :tangle ../bin/publish.el :comments noweb
     (require 'ox-publish)
     (setq org-publish-project-alist
           `(("SPARC-anatomy"
              :components ("page"))
             ("page"
              :base-directory "../resources"
              :base-extension "org"
              :exclude ".*"
              :include ("sawg.org")
              :publishing-directory
              ,(let ((host (getenv "AUX_RESOLVER_HOST")))
                (format "/ssh:%s|sudo:nginx@%s:/var/www/ontology/trees/sparc/" (getenv "AUX_RESOLVER_HOST") (getenv "AUX_RESOLVER_HOST")))
              :publishing-function org-html-publish-to-html)
             ))
   #+END_SRC

   #+NAME: post-commit
   #+BEGIN_SRC bash :eval never :tangle ../bin/publish-sawg :tangle-mode (identity #o755)
     #!/usr/bin/env sh
     # this runs in the root of the git repository so we are ok
     SOURCE="${BASH_SOURCE[0]}"
     while [ -h "$SOURCE" ]; do # resolve all symlinks
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     SOURCE="$(readlink "$SOURCE")"
     [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # resolve relative symlinks
     done
     ABS_PATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

     /usr/bin/emacs -Q --batch \
         -l "${ABS_PATH}/publish.el" \
         ../resources/sawg.org \
         --funcall org-publish-all
   #+END_SRC

* Overview
  The Stimulating Peripheral Activity to Relieve Conditions (SPARC) effort is the result of National Institutes of Health’s (NIH) 
  drive to map out the neural circuitry responsible for visceral control in higher vertebrates.  The SPARC Anatomy Working Group (SAWG) 
  is headed by one of the three Data and Resource Center (DRC) cores, Map Synthesis Core (MAP-CORE). SAWG is composed of a group of 
  expert anatomists with a goal of: 

  - Compiling and extending controlled lists of anatomical terms 
  - Standardizing flat map schematics and experimental data 
  - Designing simple topological organ models and their connections  

  This page provides access to the data generated by the SAWG which includes links to documentation about vocabulary services, 
  term request and connectivity. This page will be continuously updated. 


* 1. Terminology

** 1.1 Terminology review
   If you are here to provide expert review of terminology for SPARC here is a table!

  | region | tabular      | tree        | raw |
  |--------+--------------+-------------+-----|
  | brain  | google sheet | trees/query | ttl |
  |        |              |             |     |

** 1.2 Anatomical Terminology
   a. Documentation for SPARC term requests 
      - Internal or advanced users [documentation sheet](https://docs.google.com/spreadsheets/d/1mU8Xxqt07pweDmtvdjDriuPSuw0EeGxiKC2733nOgvY/edit?usp=sharing) 
   
   b. Vocabulary-building documentation
      - Slide presentation outlining the vocabulary are [[located here],[https://docs.google.com/presentation/d/1lgjvHoYJIFXYdvY9JLO5577hO3y2rnDxUd3TRmUzLXA/edit#slide=id.p]] 
 
   c. Documentation for the adoption of InterLex terminology services
      - [[ontology documentation],[http://ontology.neuinfo.org/docs/]]  
 
   d. Tabulation of up-to-date MicroBrightField term lists by species and organ (together with acknowledgement/contact details for leads responsible for each list); 
      - visualization/tabulization of organ parts and parcellations 
      
        - [organ parts], [https://scicrunch.org/api/1/sparc-scigraph/dynamic/prod/sparc/organParts/FMA:7203]]
        - [parcellations], [https://scicrunch.org/api/1/sparc-scigraph/dynamic/prod/sparc/parcellationGraph.json]] 


   e. Up-to-date listing of terms applied to SPARC1 metadata annotation 
      - [[terms,[https://github.com/SciCrunch/sparc-curation/blob/963ddeb7b71c982ea1a449557547d6c38c96371c/sparcur/cli.py#L1162]] 
      - [[term code],[https://github.com/SciCrunch/sparc-curation/blob/963ddeb7b71c982ea1a449557547d6c3] 

   f. Up-to-date listing of terms applied to flatmap metadata annotation 
      - TBA
 
   g. Up-to-date listing of terms applied to ApiNATOMY metadata annotation 
      - TBA
      
   h. Up-to-date listing of terms applied to 3D scaffold metadata annotation
      - TBA

   i. Searchable full reference list of terms (drawn from UBERON/FMA/Nomina/atlases)
      - TBA
* 2. Connectivity
  a. Catalogue of ApiNATOMY connectivity models 
     - TBA 

  b. Text-based querying of ApiNATOMY models (and SPARC1 metadata discovery) 
     - [[Connectivity query],[http://ontology.neuinfo.org/trees/sparc/connectivity/query]]
 
  c. Flatmap-based querying of ApiNATOMY models (and SPARC1 metadata discovery) 
     - TBA 
  
* 3. Expertise
  a. Diagram/bibliography repository for flatmap construction 
     - TBA
 
  b. List of contributing experts by SAWG area (SAWG) Organization Chart 
     - TBA
 
  c. Discussion forum for requirements collection, gap analysis, feedback 
     - TBA
 
  d. Documents section: reports and other publications 
     - TBA
 
  e. Events and other announcements 
     - TBA
 
  f. Challenges: e.g. coursing of visceral autonomic nerves 
     - TBA
 
  g. Hiring 
     - TBA 
 
